<?php

/**
 * Created by PhpStorm.
 * User: wangyang
 * Date: 2018/9/14
 * Time: 10:11
 */

namespace App\Models;

use League\Flysystem\Exception;
use Illuminate\Database\Eloquent\Builder;

class MerchantAccountModel extends BaseModel
{
    protected $table;

    protected $primaryKey = 'id';

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->table = 't_user';
    }

    public function merchant()
    {
        return $this->hasOne(MerchantModel::class,'merchant_id','merchant_id');
    }

    /*
     * @param[account_sn]
     * **/
    public function getAccountBySn($accountSn)
    {
        $res = $this->where('account_sn',$accountSn)->first();

        return $res;
    }

    /*
     * 获取帐号信息~
     * **/
    public function getAccountById($id)
    {
        $res = $this->where('id',$id)->first();

        return !empty($res) ? $res->toArray() : [];
    }

    //更新数据
    public function UpdateAccount($param)
    {
        $id = $param['id'];
        unset($param['id']);
        try{
            $this->where('id',$id)->update($param);
            return true;
        }catch(Exception $e){
            return false;
        }

    }

    /*
     * 模型的 [启动] 方法
     *
     * @return void
     * **/
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('del_flag',function(Builder $builder){
            $builder->where('del_flag','=',1);
        });
    }


}